# -*- coding: utf-8 -*-
"""JSON_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ShH8Cc98YLNRVnD-s16B-xQGYE7Zr0OE
"""

# !pip install datasets==2.21.0

# from google.colab import drive
# drive.mount('/content/drive')

import requests
import json
import pandas as pd
from datasets import Dataset
import os, json

path1 = '../dataset/'
rowList = []
dir1 = os.listdir(path1)

# 관광 KVQA 데이터(동부권)
# https://www.aihub.or.kr/aihubdata/data/view.do?currMenu=115&topMenu=100&aihubDataSe=data&dataSetSn=71607
for dt in dir1:
  if dt == '.ipynb_checkpoints': continue
  path2 = os.path.join(path1, dt)

  for fi in os.listdir(path2):
    json_file = os.path.join(path2, fi)
    with open(json_file, 'r', encoding='utf-8') as f:
      try:
        json_data = json.load(f)
        name = json_data['data']['place']
        for jdt in json_data['annotations']:
          columnList = []
          qs = jdt['question'][0]
          columnList.append(f"{name.rstrip()}의 {qs['question']}")
          columnList.append(qs['fact'][0])
          columnList.append(qs['answer'])

          rowList.append(columnList)

      except json.JSONDecodeError:
        print(f"{json_file} 불러오기 실패!!")

dataList = pd.DataFrame(rowList, columns=['instruction', 'input', 'output'])
result = Dataset.from_pandas(dataList)